"""add_speaker_to_userrole

Revision ID: 4c89cc4fee6d
Revises: 4e982edf2c83
Create Date: 2026-01-20 17:46:58.916362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c89cc4fee6d'
down_revision: Union[str, None] = '4e982edf2c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE userrole ADD VALUE 'SPEAKER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
