"""make_images_mandatory

Revision ID: 4e982edf2c83
Revises: aa4e1045bf5e
Create Date: 2026-01-20 16:44:40.173183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e982edf2c83'
down_revision: Union[str, None] = 'aa4e1045bf5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Set default values for existing rows
    op.execute("UPDATE events SET image_desktop = 'https://via.placeholder.com/800x600' WHERE image_desktop IS NULL")
    op.execute("UPDATE events SET image_mobile = 'https://via.placeholder.com/400x600' WHERE image_mobile IS NULL")

    op.alter_column('events', 'image_desktop',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'image_mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'image_mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'image_desktop',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
